apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <backend-image-url>
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: "db-service"
